<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Academies.Academic.Application\Academies.Academic.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Academies.BuildingBlocks.Infrastructure\Academies.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Academies.Academic.Tests" />
  </ItemGroup>
</Project>
