<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Academies.Engagement.Application\Academies.Engagement.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Academies.BuildingBlocks.Infrastructure\Academies.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
</Project>
